<?php

namespace TSProj\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Product_process_timeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductProcessTimeRepository extends EntityRepository
{
}
