<?php

namespace TSProj\ProductBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Work_statusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkStatusRepository extends EntityRepository
{
}
