<?php

namespace TSProj\PeopleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmployeeStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeStatusRepository extends EntityRepository
{
}
